# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Pathway Figure OCR
tagline: Pathway figures extracted from the literature
description: Mining the published literature for pathway figures and making their contents accessible for science. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pfocr.wikipathways.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: wikipathways
github_username: wikipathways
discussion_forum: github.com/wikipathways/wikipathways-help/discussions


# Build settings
incremental: true
theme: minima 
plugins:
  # - jekyll-feed
  # - jekyll-seo-tag
  # - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-include-cache
  
assets:
  sources:
    -_assets/fonts
       
markdown: kramdown
#markdown: CommonMarkGhPages
#commonmark:
#  options: ["SMART", "FOOTNOTES"]
#  extensions: ["strikethrough", "autolink", "table", "tagfilter"]

# Keep in _site folder when rebuilding.
# Everything else in _site will be deleted, by default.
# Note: Only needed if setting up _site as separate Git repo, rather than as a branch.
#
# keep_files:
#   - LICENSE
#   - .git
#   - .gitignore

# Include in processing, despite defaults (e.g,. for _ and . files and dirs)
include:
 - ".nojekyll"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - hold_data/
  - hold_figures/
  - old_data/
  - old_figures/
  - hold/ 
  - rds/
#   - .sass-cache/
  - vendor
  - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Defaults
defaults:
  # - scope:
  #     path: ""
  #     type: "organisms"
  #   values:
  #     layout: "organism-page"
  - scope:
      path: ""
      type: "figures"
    values:
      layout: "figure-page"
  - scope:
      path: ""
    values:
      layout: "default"
      sitemap: false

# Custom collections
collections:
  # organisms:
  #   output: true
  figures:
    output: true
  browse:
    output: true
  rmd:
    output: true

